name: Build and update docs/ folder

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build (static export)
        run: npm run build

      - name: Copy out to docs
        run: |
          rm -rf docs || true
          mkdir -p docs
          cp -a out/. docs/

      - name: Commit and push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # ensure GitHub Pages does not run Jekyll on the static export
          New-Item -Path docs\.nojekyll -ItemType File -Force || echo ""
          git add -A docs
          git commit -m "chore(ci): update docs/ (static export)" || echo "No changes to commit"
          git push origin HEAD:main
